### ISSUE TITLE
Increase Awareness of Amber Framework

### ISSUE THREAD

**Issue by jpotts18** [amberframework/amber#375]
### Description

I feel that Amber has potential to be the main Crystal web framework. The time for Amber to separate itself from the pack is now! I've made a list of potential ideas for increasing awareness and adoption of Amber. 

### Awareness 

Main strategy here is go after the Crystal community and influential rubyists

- [x] Links on Crystal Lang  [Community](https://crystal-lang.org/community/) 
- [x] Guest Blog on Crystal-lang.org
- [x] Hacker News Post. There was lots of excitement about [this](https://news.ycombinator.com/item?id=13209575). A 0.4.0 release could be a good time to make a post
- [ ] Tweet Testimonials. Get a tweet from a [Top 50 Rubyists ](http://rubylearning.com/blog/2008/10/29/50-rubyists-to-follow-on-twitter/) and make a twitter testimonial section.
- [ ] Ask for Code Review or Security Audit from Rails Team, Heroku member.

### Interest 

Main strategy is show legitimacy through social proof, quality documentation, and vibrant community

- [x] Compile a list of companies using this in production.
- [ ] Create a sample application that can be deployed to Heroku with a [Deploy Button](https://blog.heroku.com/heroku-button)
- [ ] Tutorial examples similar to [RailsApps](http://railsapps.github.io/)
- [ ] Create an example application that uses

### Conclusion

I'd be interested to hear what your thoughts are on this and how I could help.

**Comment by faustinoaq** [comment]
@jpotts18 Thank you for open this issue, I would suggest to fix some issues before this _marketing strategy_:

- [ ] https://github.com/amberframework/amberframework.org/issues/57 **Create Documentation, Guides and API:** This is the most important for me, because our current guide page overlaps with Gitbook documentation, so we don't have it properly organized. We can publish a guide on main website (like tutorials) and keep using Gitbook for deep documentation. Also we need to comment our code and generate an API using `crystal doc`.
- [ ] https://github.com/amberframework/amber/issues/273 Look into TechEmpower Benchmarks slowness
- [ ] https://github.com/amberframework/amber/issues/269 Provide project type option - Web vs Api 
- [ ] https://github.com/amberframework/amber/issues/347 Allow hot code reloading using Amber tasks 
- [ ] https://github.com/amberframework/amber/issues/346 Improve amber logs
- [ ] https://github.com/amberframework/amber/issues/334 Amber repository size is huge 

Another 2 things we can have in the future and that will boost amber popularity are the parallelism and Windows support, but we depend on crystal for these ones.

**Comment by elorest** [comment]
#269 Provide project type option - Web vs Api
We do need the ability to generate api scaffolds and controllers. This is a lot easier now that we have respond with. Creating Web vs API projects doesn't make sense on a platform where you can define your pipelines per routes.

#347 Allow hot code reloading using Amber tasks
Sounds like a sweet feature but I wouldn't put it at a higher priority than increasing awareness.

**Comment by marksiemers** [comment]
@jpotts18 - Thanks for this issue. We are looking to promote soon. Some people on the team have reached out to "influencers" to see if we can convince them about amber, then to promote it.

Of course, there is a little trepidation since the framework "isn't done" - but of course, no software product ever is.

I agree, upon the next patch release, we should push it.

**Comment by faustinoaq** [comment]
[WIP] Getting Started Updates- https://github.com/amberframework/online-docs/pull/43

**Comment by marksiemers** [comment]
Update with questions:
> Links on Crystal Lang Community

@jpotts18 - Where would this go on that page? I don't think Manas would put it under "CRYSTAL SHARDS, TOOLS AND TUTORIALS"

> Guest Blog on Crystal-lang.org

I have a guest post pending publication titled: "Top 5 Reasons for Ruby-ists to Use Crystal" which mentions Amber. There will be an amber specific blog post later this month. @robacarp - Can you confirm that you are working on that?

> Hacker News Post. There was lots of excitement about this. A 0.4.0 release could be a good time to make a post

We're past the 0.4.0 release. @amberframework/core-team - do you think we should post on hacker news, or wait for 0.7.0?

> Tweet Testimonials. Get a tweet from a Top 50 Rubyists and make a Twitter testimonial section.

I haven't been able to get a Top 50 Ruby-ist, anyone else? @amberframework/core-team 

Manas may be willing to tweet about it. They have been very open to guest blog posts and may want a more active twitter feed as well.

> Ask for Code Review or Security Audit from Rails Team, a Heroku member.

Not sure on this one @jpotts18 do you have any suggestions on how to request this?

**Comment by eliasjpr** [comment]
@marksiemers 

> do you think we should post on hacker news, or wait for 0.7.0?
- We should post on hacker news.

**Comment by eliasjpr** [comment]
@jpotts18 still interested on helping? 😄

**Comment by marksiemers** [comment]
@eliasjpr - For hacker news, should the blog post go there? https://amberframework.org/blog/2018/01/08/amber-new-releases-new-year#section-content

Or wait for @robacarp to have his published on crystal's website?

**Comment by marksiemers** [comment]
@faustinoaq - What do you think about having ambrockets be an app with a deploy to heroku button?

With the amber build pack it shouldn't be much of a problem.

**Comment by faustinoaq** [comment]
> What do you think about having ambrockets be an app with a deploy to heroku button?

I completely agree, I need to enhance ambrocket, though

> [Says the guy whose never created a heroku deploy button app]

Me too 😅

**Comment by eliasjpr** [comment]
I think it is straight forward https://devcenter.heroku.com/articles/heroku-button

**Comment by eliasjpr** [comment]
See also https://devcenter.heroku.com/articles/app-json-schema

**Comment by marksiemers** [comment]
@faustinoaq - Do you want to write an amber blog post about ambrockets and get a heroku deploy button working for it?

**Comment by marksiemers** [comment]
@elorest - Are you able to write anything about amber in use at your company?

**Comment by faustinoaq** [comment]
>  Do you want to write an amber blog post about ambrockets and get a heroku deploy button working for it?

@marksiemers Yeah, give me one week more, I will write something at nights 😅 

I shared the starting document on gitter team 👍

**Comment by faustinoaq** [comment]
We are using https://amberframework.gitbook.io/amber now :tada: 

This ways is easier to read, maintain and contribute :sparkles: 

![screenshot_20180514_215014](https://user-images.githubusercontent.com/3067335/40034059-c990eb4e-57c0-11e8-930f-b9624fa35c4a.png)

I love the new and shiny `Edit on Github` button :100:  thanks to GitbookIO :1st_place_medal:

**Comment by rishavs** [comment]
One of the most important tasks to do, IMO is to create an Amber [Realworld](https://github.com/gothinkster/realworld) app and write a step by step tutorial for it. I usually work in the JS ecosystem and I rely a lot on the realworld apps. This app essentially covers every major aspect of creating a webapp using Amber.
