### ISSUE TITLE
Document merged PRs from the last month.

### ISSUE THREAD

**Issue by elorest** [amberframework/amber#384]
- [ ] Trying again to get the tests to pass predictably on linux. #383 by elorest was merged a day ago 
- [ ] Revert "cli: add "amber exec" command for executing one-liners (#352)#382 by elorest was merged 2 days ago • Review required  
- [ ] CORS headers check should be case insensitive 
#378 by fridgerator was merged 2 days ago • Approved  
- [ ] Set ENV["PORT"] to be used by default if defined. 
#377 by elorest was merged 24 minutes ago • Approved   0.4.0 - Features & Bugfixes
- [ ] Fix dependencies for amber projects using default app template 
#373 by faustinoaq was merged 3 days ago • Approved  
- [ ] Fixes front-end dependencies for Amber Framework 
#372 by faustinoaq was merged 13 minutes ago • Approved   0.4.0 - Features & Bugfixes
- [ ] cli: add "amber exec" command for executing one-liners (#352) 
#371 by sam0x17 was merged 2 days ago • Approved  
- [ ] Fix and update dependencies 
#370 by faustinoaq was merged 3 days ago • Approved  
- [ ] Created params object that can parse json when asked too. 
#369 by elorest was merged 3 days ago • Approved  
- [ ] Add community section 
#368 by faustinoaq was merged 5 days ago • Approved  
- [ ] Respond_with uri extensions path.[json|xml|text|txt|html] 
#367 by elorest was merged 5 days ago • Approved  
- [ ] Update font-end dependencies on app template 
#366 by faustinoaq was merged 5 days ago • Approved  
- [ ] Improved settings and fixed tests 
#364 by elorest was merged 5 days ago • Approved  
- [ ] [Redirect] Allows for Class and Symbol Controller name 
#363 by eliasjpr was merged 4 days ago • Approved  
- [ ] [Controller] Adds Route Helper Methods to Controller 
#362 by eliasjpr was merged 4 days ago • Approved  
- [ ] web socket missing let declaration 
#361 by drujensen was merged 3 days ago • Approved  
- [ ] Update tagline 
#360 by marksiemers was merged 7 days ago • Approved  
- [ ] Allow multiple pipelines to be added with one block 
#359 by marksiemers was merged 3 days ago • Approved  
- [ ] Organizes Controllers Helper Methods 
#357 by eliasjpr was merged 8 days ago • Approved  
- [ ] Fixed csrf delete for generated scaffolding 
#356 by elorest was merged 10 days ago • Approved  
- [ ] Centered logo README 
#355 by faustinoaq was merged 8 days ago • Approved  
- [ ] cli: implement `db create/drop` for sqlite3 
#351 by nathanj was merged 4 days ago • Approved  
- [ ] merge docker files 
#350 by drujensen was merged 8 days ago • Approved  
- [ ] Update dependencies 
#349 by faustinoaq was merged 9 days ago • Approved  
- [ ] Clean Up and Dry Tests 
#344 by eliasjpr was merged 11 days ago • Approved  
- [ ] Use table name as part of database index name (#336) 
#340 by marksiemers was merged 12 days ago • Approved  
- [ ] Format comments using JSDoc pattern 
#338 by faustinoaq was merged 12 days ago • Approved  
- [ ] Fix missing require for task runner 
#335 by eliasjpr was merged 16 days ago • Approved  
- [ ] Fix postgresql database naming convention 
#332 by marksiemers was merged 12 days ago • Approved  
- [ ] Better Request Parsing Parameters 
#331 by drujensen was merged 16 days ago • Changes requested  
- [ ] Have generators handle multi-word names (#316) 
#330 by marksiemers was merged 13 days ago • Approved  
- [ ] Fixed an issue I found with render if we use namespaces. 
#328 by elorest was merged 18 days ago • Approved  
- [ ] @drujensen   @eliasjpr   @fridgerator Update jQuery and Bootstrap versions 
#325 by faustinoaq was merged 21 days ago • Approved  
- [ ] Fix version numbers 
#319 by faustinoaq was merged 16 days ago • Approved  
- [ ] Adds Amber Task Runner 
#318 by eliasjpr was merged 17 days ago • Approved  
- [ ] Fix typo on html code 
#314 by faustinoaq was merged 19 days ago • Approved  
- [ ] Methods to set content type and content 
#313 by elorest was merged 9 days ago • Approved  
- [ ] Fixes a typo in the home/index ECR template 
#312 by aarongodin was merged 26 days ago • Approved  
- [ ] Ensures method missing returns Bool Type 
#309 by eliasjpr was merged 27 days ago • Approved  
- [ ] Fixes bug with release being undefined and adds --no-debug to production run 
#307 by elorest was merged 27 days ago • Approved
