### ISSUE TITLE
Pull Requests which need to be documented before release.

### ISSUE THREAD

**Issue by elorest** [amberframework/amber#385]
List of PR's that still need documented.
_________________________________________

Please check off once it's documented or you're sure it doesn't need to be documented.
- [x] Update all links that points to the old gitter channel to be the new channel url 
- [x] Allow multiple pipelines to be added with one block #359 by marksiemers was merged 3 days ago 
- [x] Use table name as part of database index name (#336) #340 by marksiemers was merged 12 days ago 
- [x] Fix postgresql database naming convention #332 by marksiemers was merged 12 days ago 
- [x] Have generators handle multi-word names (#316) #330 by marksiemers was merged 13 days ago 
- [x] Created params object that can parse json when asked too.  #369 by elorest was merged 3 days ago 
- [x] Respond_with uri extensions path.[json|xml|text|txt|html] #367 by elorest was merged 5 days ago 
- [x] Fixed an issue I found with render if we use namespaces.  #328 by elorest was merged 18 days ago 
- [x] Methods to set content type and content #313 by elorest was merged 9 days ago 
- [x] cli: add "amber exec" command for executing one-liners (#352) #371 by sam0x17 was merged 2 days ago 
- [x] Adds Amber Task Runner #318 by eliasjpr was merged 17 days ago 
- [x] Fix missing require for task runner #335 by eliasjpr was merged 16 days ago 
- [x] CORS headers check should be case insensitive #378 by fridgerator was merged 2 days ago 
- [x] [Redirect] Allows for Class and Symbol Controller name #363 by eliasjpr was merged 4 days ago 
- [ ] [Controller] Adds Route Helper Methods to Controller #362 by eliasjpr was merged 4 days ago 
- [x] web socket missing let declaration #361 by drujensen was merged 3 days ago 
- [x] Better Request Parsing Parameters #331 by drujensen was merged 16 days ago
- [x] merge docker files #350 by drujensen was merged 8 days ago 
- [x] Trying again to get the tests to pass predictably on linux.  #383 by elorest was merged a day ago 
- [x] Revert "cli: add "amber exec" command for executing one-liners (#352)" #382 by elorest was merged 2 days ago 
- [x] Set ENV["PORT"] to be used by default if defined.  #377 by elorest was merged 24 minutes ago  0.4.0 - Features & Bugfixes
- [x] Fix dependencies for amber projects using default app template #373 by faustinoaq was merged 3 days ago 
- [x] Fixes front-end dependencies for Amber Framework #372 by faustinoaq was merged 13 minutes ago  0.4.0 - Features & Bugfixes
- [x] Fix and update dependencies #370 by faustinoaq was merged 3 days ago 
- [x] Add community section #368 by faustinoaq was merged 5 days ago 
- [x] Update font-end dependencies on app template #366 by faustinoaq was merged 5 days ago 
- [x] Improved settings and fixed tests #364 by elorest was merged 5 days ago 
- [x] Update tagline #360 by marksiemers was merged 7 days ago 
- [x] Organizes Controllers Helper Methods #357 by eliasjpr was merged 8 days ago 
- [x] Fixed csrf delete for generated scaffolding #356 by elorest was merged 10 days ago 
- [x] Centered logo README #355 by faustinoaq was merged 8 days ago 
- [x] cli: implement `db create/drop` for sqlite3 #351 by nathanj was merged 4 days ago 
- [x] Update dependencies #349 by faustinoaq was merged 9 days ago 
- [x] Clean Up and Dry Tests #344 by eliasjpr was merged 11 days ago 
- [x] Format comments using JSDoc pattern #338 by faustinoaq was merged 12 days ago 
- [x] @drujensen   @eliasjpr   @fridgerator Update jQuery and Bootstrap versions #325 by faustinoaq was merged 21 days ago 
- [x] Fix version numbers #319 by faustinoaq was merged 16 days ago 
- [x] Fix typo on html code #314 by faustinoaq was merged 19 days ago 
- [x] Fixes a typo in the home/index ECR template #312 by aarongodin was merged 26 days ago 
- [x] Ensures method missing returns Bool Type #309 by eliasjpr was merged 27 days ago 
- [x] Fixes bug with release being undefined and adds --no-debug to production run #307 by elorest was merged 27 days ago

**Comment by eliasjpr** [comment]
Since 0.3.5 is a patch, this issue should be the requirement for 0.4.0

**Comment by eliasjpr** [comment]
We need to look into this list and see if we are missing anything outstanding
