### ISSUE TITLE
Proposal for the MacPorts work

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#890]
### Description

By @conradwt on https://github.com/amberframework/amber/pull/879#issuecomment-399508039

> Should I create another issue or proposal for the MacPorts work and someone can simply assign that task to me?

> I should be able to create it over the weekend as the work week only allowed for light MacPorts research and it appears to be a straight forward process.

### Steps to Reproduce

Not applicable (not a bug)

### Versions

Amber v0.8.0 (Yay! :tada: )

### Additional Information

What is MacPorts?

The MacPorts Project is an open-source community initiative to design an easy-to-use system for compiling, installing, and upgrading either command-line, X11 or Aqua based open-source software on the Mac operating system.

See more here: https://www.macports.org/

**Comment by conradwt** [comment]
Here's the current status:

# Dependencies

- https://github.com/crystal-lang/shards/pull/214

# Tasks

## Shards

- [x] updated Shards project  (i.e. sources and docs)

- [x] submitted PR to Shards project

- [ ] approved PR to Shards project

- [x] created the Shards Portfile

- [ ] submitted PR to MacPorts project

## Amber

- [ ] updated Amber project (i.e. sources and docs)

- [ ] submitted PR to Amber project

- [ ] approved PR to Shards project

- [x] create the Amber Portfile

- [ ] submitted PR to MacPorts project

**Comment by conradwt** [comment]
@faustinoaq I was able to submit a PR to the MacPorts team.  However, it seems that the Amber CLI only needs a subset of the Amber web framework code.  Do you think that the `Makefile` installs too many `shards` for the CLI to work at this time?  For example, snippet from the installation of the `amber` port on my system:

```
Fetching https://github.com/mosop/cli.git
Fetching https://github.com/mosop/optarg.git
Fetching https://github.com/mosop/callback.git
Fetching https://github.com/mosop/string_inflection.git
Fetching https://github.com/elorest/compiled_license.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/TechMagister/liquid.cr.git
Fetching https://github.com/phoffer/inflector.cr.git
Fetching https://github.com/amberframework/micrate.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-mysql.git
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/stefanwille/crystal-redis.git
Fetching https://github.com/ysbaddaden/pool.git
Fetching https://github.com/jwaldrip/shell-table.cr.git
Fetching https://github.com/jeromegn/slang.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/mosop/teeplate.git
Fetching https://github.com/veelenga/ameba.git
Using amber_router (0.1.0)
Using cli (0.7.0)
Using optarg (0.5.8)
Using callback (0.6.3)
Using string_inflection (0.2.1)
Using compiled_license (0.1.3)
Using kilt (0.4.0)
Using liquid (0.3.0)
Using inflector (0.1.8)
Using micrate (0.3.3)
Using db (0.5.0)
Using mysql (0.5.0)
Using pg (0.15.0)
Using redis (2.0.0)
Using pool (0.2.3)
Using shell-table (0.9.2)
Using slang (1.7.1)
Using sqlite3 (0.10.0)
Using teeplate (0.6.1)
Using ameba (0.7.0)
```

What do you think?  This many only require a few tweaks to the `Makefile` because one tends to do the following:

1) . create an Amber app

2) . cd into the apps directory

3).  install shards

I was thinking that step (3) could be performed automatically based on the options provided in step (1).  Just thinking out load here.
